.build-template: &build-template
    before_script:
        - sudo pip install --upgrade setuptools twine wheel
    script:
        - python3 setup.py sdist bdist_wheel
        - twine upload dist/*

gcc-8:
    image: conanio/gcc8
    variables:
        CONAN_GCC_VERSIONS: "8"
    <<: *build-template

